// TEMPLATE: Integration test pattern for PostgresApplicationRepository.
//
// This file is a REFERENCE IMPLEMENTATION — it demonstrates the test structure,
// SQL patterns, and tenant-isolation verification approach. It is NOT runnable
// as-is because createTestDatabase() throws until wired to your actual test DB.
//
// To use as a starting point:
//   1. Copy to a real test file (e.g. applications.repository.test.ts)
//   2. Replace createTestDatabase() with your test DB fixture (pg-mem or real PG)
//   3. Ensure DATABASE_URL is set in your test environment
//
// What this demonstrates:
//   - Real DB with transaction-rollback isolation (no shared state between tests)
//   - Tenant isolation at the repository layer (cross-tenant returns null)
//   - Soft-delete enforcement
//   - Optimistic locking via version column
//   - Composite PK isolation on idempotency_keys table
//
// Requires: PostgreSQL service container (see .github/workflows/ci.yml)

import { afterEach, beforeEach, describe, expect, it } from 'vitest'

// Re-use the existing domain types and repository
import type { Application, ApplicationStatus } from '../../../packages/domain/src/application.js'
import {
  PostgresApplicationRepository,
  type ApplicationRepository,
  type CreateApplicationInput,
} from './applications.repository.js'

// Minimal test DB wrapper — replace with your actual test DB setup.
// Assumes a test DB is available at DATABASE_URL from env.
interface TestDatabase {
  execute(sql: string, params?: unknown[]): Promise<void>
  queryOne<T>(sql: string, params?: unknown[]): Promise<T | null>
  begin(): Promise<void>
  rollback(): Promise<void>
}

async function createTestDatabase(): Promise<TestDatabase> {
  // Dynamically import the DB driver — swap for your actual driver.
  // This is a stub; wire to your test DB fixture (e.g. pg-mem, or a real test PG instance).
  throw new Error(
    'createTestDatabase() must be wired to your test DB fixture. ' +
    'Use pg-mem for unit-level integration tests, or a real test PostgreSQL ' +
    'instance for full-stack integration tests (as used in CI).',
  )
}

// Factory: creates two isolated tenant fixtures with users and candidates.
async function createTenantFixtures(
  db: TestDatabase,
): Promise<{ tenantA: TenantContext; tenantB: TenantContext }> {
  const tenantA = await createTenant(db, 'Tenant A')
  const tenantB = await createTenant(db, 'Tenant B')
  return { tenantA, tenantB }
}

interface TenantContext {
  tenantId: string
  userId: string
  candidateId: string
  requisitionId: string
}

async function createTenant(
  db: TestDatabase,
  _name: string,
): Promise<TenantContext> {
  // Create tenant, user, candidate, and requisition for this test tenant.
  // IDs are UUIDs generated by the DB — we read them back to use in assertions.
  await db.execute(`BEGIN`)
  const tenantId = await db.queryOne<{ id: string }>(
    `INSERT INTO tenants DEFAULT VALUES RETURNING id`,
  ).then((r) => r!.id)
  const userId = await db.queryOne<{ id: string }>(
    `INSERT INTO users (tenant_id, email, name) VALUES ($1, gen_random_uuid()::text, $2) RETURNING id`,
    [tenantId, 'test@example.com'],
  ).then((r) => r!.id)
  const candidateId = await db.queryOne<{ id: string }>(
    `INSERT INTO candidates (tenant_id, name, email) VALUES ($1, $2, gen_random_uuid()::text) RETURNING id`,
    [tenantId, 'Test Candidate'],
  ).then((r) => r!.id)
  const requisitionId = await db.queryOne<{ id: string }>(
    `INSERT INTO requisitions (tenant_id, title, status) VALUES ($1, 'Test Requisition', 'active') RETURNING id`,
    [tenantId],
  ).then((r) => r!.id)
  await db.execute(`COMMIT`)

  return { tenantId, userId, candidateId, requisitionId }
}

describe('PostgresApplicationRepository — tenant isolation', () => {
  let db: TestDatabase
  let repo: ApplicationRepository
  let tenantA: TenantContext
  let tenantB: TenantContext

  beforeEach(async () => {
    // Each test gets a fresh DB connection and two new tenants.
    // BEGIN starts an explicit transaction; afterEach rolls it back.
    db = await createTestDatabase()
    await db.execute(`BEGIN`)
    ;({ tenantA, tenantB } = await createTenantFixtures(db))
    repo = new PostgresApplicationRepository({
      queryOne: (sql, params) => db.queryOne(sql, params),
      queryMany: () => { throw new Error('queryMany not implemented in test stub') },
      execute: (sql, params) => db.execute(sql, params),
    })
  })

  afterEach(async () => {
    // Rollback — discard all changes made during this test.
    // This is faster than truncating tables and ensures zero cross-test contamination.
    await db.rollback()
  })

  // ─────────────────────────────────────────────────────────────
  // findById — cross-tenant isolation
  // ─────────────────────────────────────────────────────────────

  describe('findById', () => {
    it('returns application when tenantId matches', async () => {
      const input: CreateApplicationInput = {
        tenantId: tenantA.tenantId,
        candidateId: tenantA.candidateId,
        requisitionId: tenantA.requisitionId,
        createdBy: tenantA.userId,
      }

      const created = await repo.create(input)
      const result = await repo.findById(created.id, tenantA.tenantId)

      expect(result).not.toBeNull()
      expect(result!.id).toBe(created.id)
      expect(result!.tenantId).toBe(tenantA.tenantId)
    })

    it('returns null for cross-tenant access — Tenant B cannot read Tenant A application', async () => {
      // Tenant A creates an application
      const created = await repo.create({
        tenantId: tenantA.tenantId,
        candidateId: tenantA.candidateId,
        requisitionId: tenantA.requisitionId,
        createdBy: tenantA.userId,
      })

      // Tenant B uses their own tenantId to find the application.
      // Repository MUST return null — NOT Tenant A's data, NOT an error.
      // The 403/404 distinction is made at the route/service layer;
      // the repository layer's contract is: wrong tenantId → null.
      const result = await repo.findById(created.id, tenantB.tenantId)
      expect(result).toBeNull()
    })

    it('returns null for soft-deleted applications even with correct tenant', async () => {
      const created = await repo.create({
        tenantId: tenantA.tenantId,
        candidateId: tenantA.candidateId,
        requisitionId: tenantA.requisitionId,
        createdBy: tenantA.userId,
      })

      // Soft-delete: set deleted_at directly in the DB (repo doesn't expose soft-delete publicly)
      await db.execute(
        `UPDATE applications SET deleted_at = NOW() WHERE id = $1`,
        [created.id],
      )

      // Even the owning tenant should not see soft-deleted records
      const result = await repo.findById(created.id, tenantA.tenantId)
      expect(result).toBeNull()
    })

    it('returns null for non-existent ID even with valid tenantId', async () => {
      const result = await repo.findById(
        '00000000-0000-0000-0000-000000000000',
        tenantA.tenantId,
      )
      expect(result).toBeNull()
    })
  })

  // ─────────────────────────────────────────────────────────────
  // findActiveForCandidate — tenant scoping
  // ─────────────────────────────────────────────────────────────

  describe('findActiveForCandidate', () => {
    it('finds active application for the correct tenant', async () => {
      const created = await repo.create({
        tenantId: tenantA.tenantId,
        candidateId: tenantA.candidateId,
        requisitionId: tenantA.requisitionId,
        createdBy: tenantA.userId,
      })

      const result = await repo.findActiveForCandidate(
        tenantA.candidateId,
        tenantA.requisitionId,
        tenantA.tenantId,
      )

      expect(result).not.toBeNull()
      expect(result!.id).toBe(created.id)
    })

    it('returns null when Tenant B has no application for Tenant A candidate', async () => {
      // Tenant A has a candidate
      await repo.create({
        tenantId: tenantA.tenantId,
        candidateId: tenantA.candidateId,
        requisitionId: tenantA.requisitionId,
        createdBy: tenantA.userId,
      })

      // Tenant B checks if that candidate has an active application for them
      // (they should not — the candidate belongs to Tenant A)
      const result = await repo.findActiveForCandidate(
        tenantA.candidateId,     // Tenant A's candidate
        tenantA.requisitionId, // Tenant A's requisition
        tenantB.tenantId,        // Tenant B's tenant context
      )

      expect(result).toBeNull()
    })
  })

  // ─────────────────────────────────────────────────────────────
  // create — tenant ownership enforced at insert time
  // ─────────────────────────────────────────────────────────────

  describe('create', () => {
    it('assigns the correct tenantId to the created application', async () => {
      const created = await repo.create({
        tenantId: tenantA.tenantId,
        candidateId: tenantA.candidateId,
        requisitionId: tenantA.requisitionId,
        createdBy: tenantA.userId,
      })

      // Re-read to confirm tenantId is stored correctly
      const result = await repo.findById(created.id, tenantA.tenantId)
      expect(result!.tenantId).toBe(tenantA.tenantId)
    })
  })

  // ─────────────────────────────────────────────────────────────
  // updateStatus — tenant scoping + optimistic locking
  // ─────────────────────────────────────────────────────────────

  describe('updateStatus', () => {
    it('updates status for the correct tenant and version', async () => {
      const created = await repo.create({
        tenantId: tenantA.tenantId,
        candidateId: tenantA.candidateId,
        requisitionId: tenantA.requisitionId,
        createdBy: tenantA.userId,
      })

      const updated = await repo.updateStatus(
        created.id,
        tenantA.tenantId,
        'active',
        1, // expected version
      )

      expect(updated).not.toBeNull()
      expect(updated!.status).toBe('active')
      expect(updated!.version).toBe(2) // incremented
    })

    it('returns null when version does not match (optimistic lock)', async () => {
      const created = await repo.create({
        tenantId: tenantA.tenantId,
        candidateId: tenantA.candidateId,
        requisitionId: tenantA.requisitionId,
        createdBy: tenantA.userId,
      })

      // Try to update with wrong version (another writer already updated)
      const result = await repo.updateStatus(
        created.id,
        tenantA.tenantId,
        'active',
        99, // wrong version
      )

      // Returns null → service throws ConflictError → client retries
      expect(result).toBeNull()
    })

    it('returns null for cross-tenant update attempt', async () => {
      const created = await repo.create({
        tenantId: tenantA.tenantId,
        candidateId: tenantA.candidateId,
        requisitionId: tenantA.requisitionId,
        createdBy: tenantA.userId,
      })

      // Tenant B attempts to update Tenant A's application
      const result = await repo.updateStatus(
        created.id,
        tenantB.tenantId,
        'active',
        1,
      )

      // Repository returns null (wrong tenantId → no row matched)
      expect(result).toBeNull()
    })
  })

  // ─────────────────────────────────────────────────────────────
  // Idempotency key isolation — composite PRIMARY KEY (tenant_id, key)
  // The migration defines PRIMARY KEY (tenant_id, key) on idempotency_keys.
  // These tests verify the constraint works at the DB level, not mocked.
  // ─────────────────────────────────────────────────────────────

  describe('idempotency key — cross-tenant isolation', () => {
    it('stores idempotency response for Tenant A', async () => {
      // Direct SQL to exercise the idempotency_keys table (repo doesn't expose it directly)
      await db.execute(
        `INSERT INTO idempotency_keys
           (key, tenant_id, endpoint, request_hash, response_status, response_body)
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT (tenant_id, key) DO NOTHING`,
        [
          'abc12300-0000-4000-8000-000000000000',
          tenantA.tenantId,
          '/api/v1/applications',
          'hash-a',
          201,
          JSON.stringify({ id: 'app-a' }),
        ],
      )

      // Tenant A can retrieve their cached response
      const row = await db.queryOne<{ key: string }>(
        `SELECT key FROM idempotency_keys WHERE tenant_id = $1 AND key = $2`,
        [tenantA.tenantId, 'abc12300-0000-4000-8000-000000000000'],
      )
      expect(row).not.toBeNull()
    })

    it('Tenant B cannot read Tenant A idempotency key — composite PK isolation', async () => {
      // Store a key under Tenant A
      await db.execute(
        `INSERT INTO idempotency_keys
           (key, tenant_id, endpoint, request_hash, response_status, response_body)
         VALUES ($1, $2, $3, $4, $5, $6)`,
        [
          'abc12300-0000-4000-8000-000000000000',
          tenantA.tenantId,
          '/api/v1/applications',
          'hash-a',
          201,
          JSON.stringify({ id: 'app-a' }),
        ],
      )

      // Tenant B queries with the same key but their own tenant_id.
      // The composite PK (tenant_id, key) means Tenant B's query finds NOTHING.
      const row = await db.queryOne<{ key: string }>(
        `SELECT key FROM idempotency_keys WHERE tenant_id = $1 AND key = $2`,
        [tenantB.tenantId, 'abc12300-0000-4000-8000-000000000000'],
      )
      expect(row).toBeNull()
    })

    it('same key, different tenant — INSERT succeeds for Tenant B (no collision)', async () => {
      // Tenant A stores key "shared-uuid"
      await db.execute(
        `INSERT INTO idempotency_keys
           (key, tenant_id, endpoint, request_hash, response_status, response_body)
         VALUES ($1, $2, $3, $4, $5, $6)`,
        [
          'abc12300-0000-4000-8000-000000000000',
          tenantA.tenantId,
          '/api/v1/applications',
          'hash-a',
          201,
          JSON.stringify({ id: 'app-a' }),
        ],
      )

      // Tenant B stores the same key — composite PK allows this
      // (different tenant_id → different PK value)
      await db.execute(
        `INSERT INTO idempotency_keys
           (key, tenant_id, endpoint, request_hash, response_status, response_body)
         VALUES ($1, $2, $3, $4, $5, $6)`,
        [
          'abc12300-0000-4000-8000-000000000000',
          tenantB.tenantId,
          '/api/v1/applications',
          'hash-b',
          201,
          JSON.stringify({ id: 'app-b' }),
        ],
      )

      // Both tenants have their own entry — no collision
      const count = await db.queryOne<{ count: number }>(
        `SELECT COUNT(*) as count FROM idempotency_keys WHERE key = $1`,
        ['abc12300-0000-4000-8000-000000000000'],
      )
      expect(count!.count).toBe(2)
    })
  })
})
